version: '3'
services:
   fp-cloudconfig:
    image: focalpoint/fp-cloudconfig
    ports:
     - "8888:8888"
   fp-eureka:
    image: focalpoint/fp-eureka
    ports:
     - "1111:1111"
    depends_on:
     - fp-cloudconfig
    command: ["./wait-for-it.sh", "fp-cloudconfig:8888", "--", "python", "app.py"]
   fp-apigateway:
    image: focalpoint/fp-apigateway
    ports:
     - "8181:8181"
    depends_on:
     - fp-eureka
    command: ["./wait-for-it.sh", "fp-eureka:1111", "--", "python", "app.py"]
   fp-service-admin:
    image: focalpoint/fp-service-admin
    mode: replicated
      replicas: 3
    depends_on:
     - fp-eureka
    command: ["./wait-for-it.sh", "fp-eureka:1111", "--", "python", "app.py"]
    deploy: